CREATE TABLE `MEMBER` (
	`MEM_NO`	INT	NOT NULL,
	`MEM_PWD`	VARCHAR(30)	NOT NULL,
	`MEM_NAME`	VARCHAR(30)	NOT NULL,
	`MEM_ADD`	VARCHAR(30)	NOT NULL,
	`MEM_EMAIL`	VARCHAR(30)	NOT NULL,
	`MEM_GENDER`	VARCHAR(1)	NOT NULL	COMMENT '남자(M), 여자(F)',
	`MEM_PHONE`	VARCHAR(13)	NOT NULL	COMMENT 'XXX-XXXX-XXXX',
	`MEM_STATUS`	VARCHAR(1)	NOT NULL	DEFAULT Y	COMMENT 'A(시스템 관리자), Y(활동), N(탈퇴), B(정지),M(구장 관리자)',
	`MEM_RANK`	DOUBLE	NOT NULL	DEFAULT 0,
	`MEM_ENROLL_DATE`	DATE	NOT NULL	DEFAULT SYSDATE,
	`MEM_BIRTH`	DATE	NOT NULL
);

CREATE TABLE `PROFILE_FILE` (
	`FILE_NO`	INT	NOT NULL,
	`MEM_NO`	INT	NULL,
	`TEAM_NO`	INT	NULL,
	`ORIGIN_NAME`	VARCHAR(30)	NOT NULL,
	`CHANGE_NAME`	VARCHAR(30)	NOT NULL,
	`FILE_PATH`	VARCHAR(30)	NOT NULL
);

CREATE TABLE `STADIUM` (
	`STADIUM_NO`	INT	NOT NULL,
	`MEM_NO`	INT	NOT NULL	COMMENT '구장 관리자 식별 번호',
	`STADIUM_NAME`	VARCHAR(100)	NOT NULL,
	`STADIUM_ADDRESS`	VARCHAR(40)	NOT NULL,
	`STADIUM_ZIPCODE`	INT	NOT NULL,
	`STADIUM_SCORE`	DOUBLE	NOT NULL	DEFAULT 0,
	`STADIUM_PRICE`	INT	NOT NULL	DEFAULT 0,
	`STADIUM_CATEGORY`	VARCHAR(20)	NOT NULL,
	`STADIUM_START_TIME`	TIME	NOT NULL,
	`STADIUM_END_TIME`	TIME	NOT NULL,
	`STATUS`	VARCHAR(1)	NOT NULL	DEFAULT Y
);

CREATE TABLE `TEAM` (
	`TEAM_NO`	INT	NOT NULL,
	`TEAM_NAME`	VARCHAR(20)	NOT NULL,
	`TEAM_EXPLAN`	TEXT	NULL,
	`TEAM_MAX_PERSON`	INT	NOT NULL	COMMENT '구단 수용 최대 인원수',
	`TEAM_TYPE`	VARCHAR(20)	NOT NULL	COMMENT '축구, 야구, 농구, 풋살',
	`ACTIVITY_DAYS`	TEXT	NULL,
	`ACTIVITY_TIME`	TEXT	NULL,
	`ACTIVITY_AREA`	TEXT	NULL,
	`STATUS`	VARCHAR(1)	NOT NULL	DEFAULT Y,
	`SCORE`	DOUBLE	NOT NULL	DEFAULT 0,
	`TEAM_POINT`	INT	NOT NULL	DEFAULT 0,
	`TEAM_ENROLL_DATE`	DATE	NOT NULL	DEFAULT SYSDATE,
	`APPLICATION`	VARCHAR(1)	NOT NULL	DEFAULT N,
	`MEM_NO`	INT	NOT NULL	COMMENT '구단장'
);

CREATE TABLE `TEAM_MEMBER` (
	`TEAM_NO`	INT	NOT NULL,
	`MEM_NO`	INT	NOT NULL,
	`STATUS`	VARCHAR(1)	NOT NULL	DEFAULT Y,
	`MEM_ENROLL_DATE`	DATE	NOT NULL	DEFAULT SYSDATE,
	`APPROVE`	DATETIME	NOT NULL	DEFAULT SYSDATE
);

CREATE TABLE `TEAM_IMG` (
	`TEAM_NO`	INT	NOT NULL,
	`ORIGIN_NAME`	VARCHAR(30)	NOT NULL,
	`CHANGE_NAME`	VARCHAR(30)	NOT NULL,
	`FILE_PATH`	VARCHAR(30)	NOT NULL,
	`FILE_LEVER`	VARCHAR(1)	NULL	COMMENT '(1 : 썸네일, 2: 이미지, 3 : 구단 프로필)',
	`STATUS`	VARCHAR(1)	NOT NULL	DEFAULT Y
);

CREATE TABLE `MATCH` (
	`MATCH_NO`	INT	NOT NULL,
	`MEM_NO`	INT	NOT NULL	COMMENT '구장 관리자 식별 번호',
	`STADIUM_NO`	INT	NOT NULL,
	`TEAM_A_NO`	INT	NOT NULL,
	`TEAM_B_NO`	INT	NULL,
	`SCORE_A`	INT	NULL,
	`SCORE_B`	INT	NULL,
	`CATEGORY`	VARCHAR(30)	NOT NULL,
	`RESERV_START`	DATE	NULL,
	`RESERV_END`	DATE	NULL,
	`ACCESS_DATE`	DATETIME	NULL	DEFAULT SYSDATE
);

CREATE TABLE `MATCH_QNA` (
	`MATCH_QNA_NO`	INT	NOT NULL,
	`MATCH_NO`	INT	NOT NULL,
	`Q_MEM_NO`	INT	NOT NULL	COMMENT '선수 식별 번호',
	`A_MEM_NO`	INT	NOT NULL	COMMENT '심판 식별 번호',
	`MATCH_Q_TITLE`	VARCHAR(255)	NOT NULL,
	`MATCH_Q_DETAIL`	VARCHAR(1000)	NOT NULL,
	`MATCH_A`	VARCHAR(1000)	NULL	DEFAULT NULL	COMMENT '답변',
	`MATCH_QNA_DATE`	DATETIME	NOT NULL	DEFAULT SYSDATE,
	`MEM_NO2`	INT	NOT NULL	COMMENT '구장 관리자 식별 번호'
);

CREATE TABLE `BOARD` (
	`BOARD_NO`	INT	NOT NULL,
	`MEM_NO`	INT	NOT NULL,
	`TITLE`	VARCHAR(30)	NOT NULL,
	`CONTENT`	VARCHAR(2000)	NULL,
	`CREATE_DATE`	DATE	NOT NULL,
	`MODIFY_DATE`	DATE	NULL,
	`VIEW`	INT	NULL	DEFAULT 0,
	`LIKE`	INT	NULL	DEFAULT 0,
	`TYPE`	VARCHAR(20)	NOT NULL	DEFAULT 기타,
	`STATUS`	VARCHAR(1)	NULL	DEFAULT Y
);

CREATE TABLE `BOARD_FILE` (
	`FILE_NO`	INT	NOT NULL,
	`REF_BOARD_NO`	INT	NULL,
	`REF_TEAM_BOARD_NO`	INT	NOT NULL,
	`ORIGIN_NAME`	VARCHAR(30)	NOT NULL,
	`CHANGE_NAME`	VARCHAR(30)	NOT NULL,
	`FILE_PATH`	VARCHAR(30)	NOT NULL,
	`STATUS`	VARCHAR(1)	NOT NULL	DEFAULT Y
);

CREATE TABLE `BOARD_COMMENT` (
	`COM_NO`	INT	NOT NULL,
	`REF_BOARD_NO`	INT	NOT NULL,
	`MEM_NO`	INT	NOT NULL,
	`COM_CREATE_DATE`	DATE	NOT NULL,
	`COM_MODIFY_DATE`	DATE	NULL,
	`STATUS`	VARCHAR(1)	NOT NULL	DEFAULT Y,
	`COM_PARENT_NO`	INT	NULL	COMMENT '대댓글 부모 댓글 번호',
	`COM_CONTENT`	VARCHAR(2000)	NULL
);

CREATE TABLE `MEMBER_PENALTY` (
	`MEM_NO`	INT	NOT NULL,
	`PN_CONTENT`	VARCHAR(1000)	NULL,
	`PN_DATE`	DATE	NULL	DEFAULT SYSDATE,
	`PN_COUNT`	NUMBER	NULL	DEFAULT 0,
	`PN_TYPE`	VARCHAR(20)	NULL	COMMENT '게시판, 댓글, 심판'
);

CREATE TABLE `MATCH_BEST` (
	`MATCH_NO`	INT	NOT NULL,
	`MEM_NO`	INT	NOT NULL,
	`MEM_NO_VOTE_COUNT`	INT	NOT NULL	DEFAULT 0	COMMENT '투표 찍히면 1씩 증가',
	`VOTE_STATUS`	DATETIME	NULL	DEFAULT NULL	COMMENT 'NULL이면 투표 안함 시간이면 투표 함',
	`MEM_NO2`	INT	NOT NULL	COMMENT '구장 관리자 식별 번호'
);

CREATE TABLE `RECRUIT` (
	`APPLICATION_NO`	INT	NOT NULL,
	`TEAM_NO`	INT	NOT NULL,
	`MEM_NO`	INT	NOT NULL,
	`APPROVE_OR_NOT`	VARCHAR(1)	NOT NULL	DEFAULT N,
	`APPLICATION_DATE`	DATETIME	NOT NULL	DEFAULT SYSDATE,
	`INTRODUCE`	VARCHAR(1000)	NULL
);

CREATE TABLE `LOGIN_LOG` (
	`MEM_NO`	INT	NOT NULL,
	`LOGIN_DATE`	DATE	NOT NULL	DEFAULT SYSDATE
);

CREATE TABLE `STADIUM_IMG` (
	`IMG_NO`	INT	NOT NULL,
	`STADIUM_NO`	INT	NOT NULL,
	`ORIGIN_NAME`	VARCHAR(30)	NULL,
	`CHANGE_NAME`	VARCHAR(30)	NULL,
	`FILE_PATH`	VARCHAR(30)	NULL,
	`STATUS`	VARCHAR(1)	NOT NULL	DEFAULT Y,
	`FILE_TYPE`	INT	NULL	DEFAULT 0	COMMENT '0: 썸네일  /  1: 디테일 1 /  2: 디테일 2 /  3: 디테일3'
);

CREATE TABLE `TEAM_BOARD` (
	`BOARD_NO`	INT	NOT NULL,
	`MEM_NO`	INT	NOT NULL,
	`TEAM_NO`	INT	NOT NULL,
	`TITLE`	VARCHAR(30)	NOT NULL,
	`CONTENT`	VARCHAR(2000)	NULL,
	`CREATE_DATE`	DATE	NOT NULL,
	`MODIFY_DATE`	DATE	NULL,
	`VIEW`	INT	NULL	DEFAULT 0,
	`LIKE`	INT	NULL	DEFAULT 0,
	`TYPE`	VARCHAR(20)	NOT NULL	DEFAULT 기타,
	`STATUS`	VARCHAR(1)	NULL	DEFAULT Y
);

CREATE TABLE `TEAM_BOARD_COMMENT` (
	`COM_NO`	INT	NOT NULL,
	`REF_TEAM_BOARD_NO`	INT	NOT NULL,
	`MEM_NO`	INT	NOT NULL,
	`COM_PARENT_NO`	INT	NULL	COMMENT '대댓글 부모 댓글 번호',
	`COM_CREATE_DATE`	DATETIME	NOT NULL	DEFAULT SYSDATE,
	`COM_MODIFY_DATE`	DATETIME	NULL	DEFAULT SYSDATE,
	`STATUS`	VARCHAR(1)	NOT NULL	DEFAULT Y
);

CREATE TABLE `CATEGORY` (
	`MEM_NO`	INT	NOT NULL,
	`SOC_POSI`	VARCHAR(30)	NULL,
	`SOC_ABILITY`	VARCHAR(30)	NULL,
	`FOOT_POSI`	VARCHAR(30)	NULL,
	`FOOT_ABILITY`	VARCHAR(30)	NULL,
	`BASKET_POSI`	VARCHAR(30)	NULL,
	`BASKET_ABILITY`	VARCHAR(30)	NULL,
	`BASE_POSI`	VARCHAR(30)	NULL,
	`BASE_ABILITY`	VARCHAR(30)	NULL
);

CREATE TABLE `STADIUM_RESERVATIONS` (
	`RESERVATION_NO`	INT	NOT NULL,
	`STADIUM_NO`	INT	NOT NULL,
	`STADIUM_MEM_NO`	INT	NOT NULL	COMMENT '구장 관리자 식별 번호',
	`A_MEM_NO`	INT	NOT NULL	COMMENT 'a팀 팀장',
	`RE_WEEK`	VARCHAR(10)	NULL,
	`B_MEM_NO`	INT	NOT NULL	COMMENT 'b팀 팀장',
	`STATUS`	VARCHAR(1)	NULL	COMMENT 'Y(승인) , N(취소), NULL(대기중)',
	`PLACE_PRICE`	INT	NULL,
	`PAY_TYPE`	VARCHAR(10)	NULL,
	`START_TIME`	DATE	NULL,
	`END_TIME`	DATE	NULL
);

CREATE TABLE `STADIUM_REVIEW` (
	`REVIEW_NO`	INT	NOT NULL,
	`STADIUM_NO`	INT	NOT NULL,
	`MEM_NO`	INT	NOT NULL	COMMENT '구장 관리자 식별 번호',
	`REVIEW_STAR`	DOUBLE	NOT NULL	DEFAULT 0,
	`REVIEW_CONTENT`	VARCHAR(1000)	NULL,
	`REVIEW_DATE`	DATE	NULL
);

CREATE TABLE `STADIUM_RENTAL` (
	`STADIUM_NO`	INT	NOT NULL,
	`BALL`	VARCHAR(1)	NULL	DEFAULT N	COMMENT 'Y, N으로 구분',
	`VEST`	VARCHAR(1)	NULL	DEFAULT N	COMMENT 'Y, N으로 구분'
);

CREATE TABLE `STADIUM_ AM` (
	`STADIUM_NO`	INT	NOT NULL,
	`TOILET`	VARCHAR(1)	NULL	DEFAULT N	COMMENT 'Y, N으로 구분',
	`SHOWER`	VARCHAR(1)	NULL	DEFAULT N	COMMENT 'Y, N으로 구분',
	`SMOKE`	VARCHAR(1)	NULL	DEFAULT N	COMMENT 'Y, N으로 구분',
	`PARK`	VARCHAR(1)	NULL	DEFAULT N	COMMENT 'Y, N으로 구분',
	`DRINK`	VARCHAR(1)	NULL	DEFAULT N	COMMENT 'Y, N으로 구분'
);

ALTER TABLE `MEMBER` ADD CONSTRAINT `PK_MEMBER` PRIMARY KEY (
	`MEM_NO`
);

ALTER TABLE `PROFILE_FILE` ADD CONSTRAINT `PK_PROFILE_FILE` PRIMARY KEY (
	`FILE_NO`,
	`MEM_NO`,
	`TEAM_NO`
);

ALTER TABLE `STADIUM` ADD CONSTRAINT `PK_STADIUM` PRIMARY KEY (
	`STADIUM_NO`,
	`MEM_NO`
);

ALTER TABLE `TEAM` ADD CONSTRAINT `PK_TEAM` PRIMARY KEY (
	`TEAM_NO`
);

ALTER TABLE `MATCH` ADD CONSTRAINT `PK_MATCH` PRIMARY KEY (
	`MATCH_NO`,
	`MEM_NO`
);

ALTER TABLE `MATCH_QNA` ADD CONSTRAINT `PK_MATCH_QNA` PRIMARY KEY (
	`MATCH_QNA_NO`
);

ALTER TABLE `BOARD` ADD CONSTRAINT `PK_BOARD` PRIMARY KEY (
	`BOARD_NO`
);

ALTER TABLE `BOARD_FILE` ADD CONSTRAINT `PK_BOARD_FILE` PRIMARY KEY (
	`FILE_NO`
);

ALTER TABLE `BOARD_COMMENT` ADD CONSTRAINT `PK_BOARD_COMMENT` PRIMARY KEY (
	`COM_NO`
);

ALTER TABLE `MEMBER_PENALTY` ADD CONSTRAINT `PK_MEMBER_PENALTY` PRIMARY KEY (
	`MEM_NO`
);

ALTER TABLE `RECRUIT` ADD CONSTRAINT `PK_RECRUIT` PRIMARY KEY (
	`APPLICATION_NO`
);

ALTER TABLE `STADIUM_IMG` ADD CONSTRAINT `PK_STADIUM_IMG` PRIMARY KEY (
	`IMG_NO`
);

ALTER TABLE `TEAM_BOARD` ADD CONSTRAINT `PK_TEAM_BOARD` PRIMARY KEY (
	`BOARD_NO`
);

ALTER TABLE `TEAM_BOARD_COMMENT` ADD CONSTRAINT `PK_TEAM_BOARD_COMMENT` PRIMARY KEY (
	`COM_NO`
);

ALTER TABLE `CATEGORY` ADD CONSTRAINT `PK_CATEGORY` PRIMARY KEY (
	`MEM_NO`
);

ALTER TABLE `STADIUM_RESERVATIONS` ADD CONSTRAINT `PK_STADIUM_RESERVATIONS` PRIMARY KEY (
	`RESERVATION_NO`
);

ALTER TABLE `STADIUM_REVIEW` ADD CONSTRAINT `PK_STADIUM_REVIEW` PRIMARY KEY (
	`REVIEW_NO`
);

ALTER TABLE `PROFILE_FILE` ADD CONSTRAINT `FK_MEMBER_TO_PROFILE_FILE_1` FOREIGN KEY (
	`MEM_NO`
)
REFERENCES `MEMBER` (
	`MEM_NO`
);

ALTER TABLE `PROFILE_FILE` ADD CONSTRAINT `FK_TEAM_TO_PROFILE_FILE_1` FOREIGN KEY (
	`TEAM_NO`
)
REFERENCES `TEAM` (
	`TEAM_NO`
);

ALTER TABLE `STADIUM` ADD CONSTRAINT `FK_MEMBER_TO_STADIUM_1` FOREIGN KEY (
	`MEM_NO`
)
REFERENCES `MEMBER` (
	`MEM_NO`
);

ALTER TABLE `MATCH` ADD CONSTRAINT `FK_STADIUM_TO_MATCH_1` FOREIGN KEY (
	`MEM_NO`
)
REFERENCES `STADIUM` (
	`MEM_NO`
);

ALTER TABLE `MEMBER_PENALTY` ADD CONSTRAINT `FK_MEMBER_TO_MEMBER_PENALTY_1` FOREIGN KEY (
	`MEM_NO`
)
REFERENCES `MEMBER` (
	`MEM_NO`
);

ALTER TABLE `CATEGORY` ADD CONSTRAINT `FK_MEMBER_TO_CATEGORY_1` FOREIGN KEY (
	`MEM_NO`
)
REFERENCES `MEMBER` (
	`MEM_NO`
);

